import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// components/header
import Header from "@/components/Header";

import { JetBrains_Mono } from "next/font/google";
import PageTransition from "@/components/PageTransition";
import StariTransition from "@/components/StariTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800" ],
  variable:'--font-jetbrainsMono',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Junayed Hassan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
        <StariTransition/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
